/*
 * Copyright (C) 2017 Wilman Ortiz Navarro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package co.com.sistema.sistemainformacion.view;

/**
 *
 * @author Wilman Ortiz Navarro
 */
public class FormEstudios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormEstudios
     */
    public FormEstudios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpReferencias = new javax.swing.ButtonGroup();
        jpEstudios = new javax.swing.JPanel();
        jlbNivelEstudios = new javax.swing.JLabel();
        jcbNivelEstudios = new javax.swing.JComboBox<>();
        jlbLugarEstudios = new javax.swing.JLabel();
        jtfLugarEstudios = new javax.swing.JTextField();
        jlTituloObtenido = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jlbPeriodo = new javax.swing.JLabel();
        jftfEstudioDesde = new javax.swing.JFormattedTextField();
        jlbHasta = new javax.swing.JLabel();
        jftfEstudioHasta = new javax.swing.JFormattedTextField();
        jbtLimpiarEstudios = new javax.swing.JButton();
        jbtRegistrarEstudios = new javax.swing.JButton();
        jpOtrosEstudios = new javax.swing.JPanel();
        jlbTipoEstudio = new javax.swing.JLabel();
        jcbTipoEstudio = new javax.swing.JComboBox<>();
        jlbNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlbIntensidad = new javax.swing.JLabel();
        jtfIntensidad = new javax.swing.JTextField();
        jbtRegistrarOtros = new javax.swing.JButton();
        jbtLimpiarOtros = new javax.swing.JButton();
        jpExperiencia = new javax.swing.JPanel();
        jlbEntidad = new javax.swing.JLabel();
        jtfEntidad = new javax.swing.JTextField();
        jlbCaracter = new javax.swing.JLabel();
        jcbCaracter = new javax.swing.JComboBox<>();
        jlbduracion = new javax.swing.JLabel();
        jftfExperienciaDesde = new javax.swing.JFormattedTextField();
        jlbExperienciaHasta = new javax.swing.JLabel();
        jftfExperienciaHasta = new javax.swing.JFormattedTextField();
        jlbDescripcion = new javax.swing.JLabel();
        jspDescripcion = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jbtRegistrarLaboral = new javax.swing.JButton();
        jbtLimpiarLaboral = new javax.swing.JButton();
        jpReferenciaPersonal = new javax.swing.JPanel();
        jlbTipoReferencia = new javax.swing.JLabel();
        jrbPersonal = new javax.swing.JRadioButton();
        jrbFamiliar = new javax.swing.JRadioButton();
        jlbNombres = new javax.swing.JLabel();
        jtfNombres = new javax.swing.JTextField();
        jlbOcupacion = new javax.swing.JLabel();
        jtfOcupacion = new javax.swing.JTextField();
        jlbCelular = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jbtRegistrarReferencia = new javax.swing.JButton();
        jbtLimpiarReferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Información Laboral:");

        jpEstudios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Estudios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 15))); // NOI18N

        jlbNivelEstudios.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbNivelEstudios.setText("Nivel de Estudios:");

        jcbNivelEstudios.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbLugarEstudios.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbLugarEstudios.setText("Lugar de Estudios:");

        jtfLugarEstudios.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlTituloObtenido.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlTituloObtenido.setText("Titulo Obtenido:");

        jtfTitulo.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbPeriodo.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbPeriodo.setText("Periodo Desde:");

        jftfEstudioDesde.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbHasta.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbHasta.setText("Hasta:");

        jftfEstudioHasta.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jbtLimpiarEstudios.setText("Registrar");

        jbtRegistrarEstudios.setText("Registrar");

        javax.swing.GroupLayout jpEstudiosLayout = new javax.swing.GroupLayout(jpEstudios);
        jpEstudios.setLayout(jpEstudiosLayout);
        jpEstudiosLayout.setHorizontalGroup(
            jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstudiosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbNivelEstudios)
                    .addComponent(jlbLugarEstudios)
                    .addComponent(jlTituloObtenido)
                    .addComponent(jlbPeriodo))
                .addGap(39, 39, 39)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEstudiosLayout.createSequentialGroup()
                        .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLugarEstudios)
                            .addComponent(jtfTitulo))
                        .addGap(16, 16, 16))
                    .addGroup(jpEstudiosLayout.createSequentialGroup()
                        .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpEstudiosLayout.createSequentialGroup()
                                .addComponent(jftfEstudioDesde, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbHasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfEstudioHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                            .addComponent(jcbNivelEstudios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtRegistrarEstudios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtLimpiarEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jpEstudiosLayout.setVerticalGroup(
            jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEstudiosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNivelEstudios)
                    .addComponent(jcbNivelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLugarEstudios)
                    .addComponent(jtfLugarEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloObtenido)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPeriodo)
                    .addComponent(jlbHasta)
                    .addComponent(jftfEstudioDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfEstudioHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLimpiarEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jbtRegistrarEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpOtrosEstudios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Otros Estudios: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 15))); // NOI18N

        jlbTipoEstudio.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbTipoEstudio.setText("Tipo: ");

        jcbTipoEstudio.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbNombre.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbNombre.setText("Nombre:");

        jtfNombre.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbIntensidad.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbIntensidad.setText("Intensidad");

        jtfIntensidad.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jbtRegistrarOtros.setText("Registrar");

        jbtLimpiarOtros.setText("Limpiar");

        javax.swing.GroupLayout jpOtrosEstudiosLayout = new javax.swing.GroupLayout(jpOtrosEstudios);
        jpOtrosEstudios.setLayout(jpOtrosEstudiosLayout);
        jpOtrosEstudiosLayout.setHorizontalGroup(
            jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOtrosEstudiosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTipoEstudio)
                    .addComponent(jlbNombre)
                    .addComponent(jlbIntensidad))
                .addGap(96, 96, 96)
                .addGroup(jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTipoEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIntensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpOtrosEstudiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtRegistrarOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtLimpiarOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpOtrosEstudiosLayout.setVerticalGroup(
            jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOtrosEstudiosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoEstudio)
                    .addComponent(jcbTipoEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombre))
                .addGap(22, 22, 22)
                .addGroup(jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfIntensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbIntensidad))
                .addGap(47, 47, 47)
                .addGroup(jpOtrosEstudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLimpiarOtros, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jbtRegistrarOtros, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpExperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Experiencia Laboral:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 15))); // NOI18N

        jlbEntidad.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbEntidad.setText("Nombre de la Entidad");

        jtfEntidad.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbCaracter.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbCaracter.setText("Caracter:");

        jcbCaracter.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jcbCaracter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jlbduracion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbduracion.setText("Periodo Desde: ");

        jftfExperienciaDesde.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbExperienciaHasta.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbExperienciaHasta.setText("Hasta:");

        jftfExperienciaHasta.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbDescripcion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbDescripcion.setText("Descripción del Cargo: ");

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jtaDescripcion.setRows(5);
        jspDescripcion.setViewportView(jtaDescripcion);

        jbtRegistrarLaboral.setText("Registrar");

        jbtLimpiarLaboral.setText("Limpiar");

        javax.swing.GroupLayout jpExperienciaLayout = new javax.swing.GroupLayout(jpExperiencia);
        jpExperiencia.setLayout(jpExperienciaLayout);
        jpExperienciaLayout.setHorizontalGroup(
            jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExperienciaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspDescripcion)
                    .addGroup(jpExperienciaLayout.createSequentialGroup()
                        .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEntidad)
                            .addComponent(jlbDescripcion)
                            .addComponent(jlbCaracter)
                            .addComponent(jlbduracion))
                        .addGap(18, 18, 18)
                        .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpExperienciaLayout.createSequentialGroup()
                                .addComponent(jftfExperienciaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlbExperienciaHasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfExperienciaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExperienciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtRegistrarLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtLimpiarLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpExperienciaLayout.setVerticalGroup(
            jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpExperienciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEntidad)
                    .addComponent(jtfEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCaracter))
                .addGap(18, 18, 18)
                .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbduracion)
                    .addComponent(jftfExperienciaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbExperienciaHasta)
                    .addComponent(jftfExperienciaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpExperienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLimpiarLaboral, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jbtRegistrarLaboral, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpReferenciaPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referencias:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 15))); // NOI18N

        jlbTipoReferencia.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbTipoReferencia.setText("Tipo Referencia: ");

        bgpReferencias.add(jrbPersonal);
        jrbPersonal.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jrbPersonal.setText("Personal");

        bgpReferencias.add(jrbFamiliar);
        jrbFamiliar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jrbFamiliar.setText("Familiar");

        jlbNombres.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbNombres.setText("Nombres: ");

        jtfNombres.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbOcupacion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbOcupacion.setText("Ocupación: ");

        jtfOcupacion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jlbCelular.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbCelular.setText("Celular: ");

        jtfTelefono.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jbtRegistrarReferencia.setText("Registrar");

        jbtLimpiarReferencia.setText("Limpiar");

        javax.swing.GroupLayout jpReferenciaPersonalLayout = new javax.swing.GroupLayout(jpReferenciaPersonal);
        jpReferenciaPersonal.setLayout(jpReferenciaPersonalLayout);
        jpReferenciaPersonalLayout.setHorizontalGroup(
            jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReferenciaPersonalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpReferenciaPersonalLayout.createSequentialGroup()
                        .addComponent(jlbTipoReferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbPersonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbFamiliar))
                    .addGroup(jpReferenciaPersonalLayout.createSequentialGroup()
                        .addComponent(jlbNombres)
                        .addGap(36, 36, 36)
                        .addComponent(jtfNombres))
                    .addGroup(jpReferenciaPersonalLayout.createSequentialGroup()
                        .addComponent(jlbOcupacion)
                        .addGap(25, 25, 25)
                        .addComponent(jtfOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpReferenciaPersonalLayout.createSequentialGroup()
                        .addComponent(jlbCelular)
                        .addGap(51, 51, 51)
                        .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReferenciaPersonalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtRegistrarReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtLimpiarReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpReferenciaPersonalLayout.setVerticalGroup(
            jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReferenciaPersonalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoReferencia)
                    .addComponent(jrbPersonal)
                    .addComponent(jrbFamiliar))
                .addGap(18, 18, 18)
                .addGroup(jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombres))
                .addGap(18, 18, 18)
                .addGroup(jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbOcupacion)
                    .addComponent(jtfOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCelular))
                .addGap(80, 80, 80)
                .addGroup(jpReferenciaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLimpiarReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jbtRegistrarReferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpEstudios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpOtrosEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpReferenciaPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpOtrosEstudios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpExperiencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpReferenciaPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpReferencias;
    private javax.swing.JButton jbtLimpiarEstudios;
    private javax.swing.JButton jbtLimpiarLaboral;
    private javax.swing.JButton jbtLimpiarOtros;
    private javax.swing.JButton jbtLimpiarReferencia;
    private javax.swing.JButton jbtRegistrarEstudios;
    private javax.swing.JButton jbtRegistrarLaboral;
    private javax.swing.JButton jbtRegistrarOtros;
    private javax.swing.JButton jbtRegistrarReferencia;
    private javax.swing.JComboBox<String> jcbCaracter;
    private javax.swing.JComboBox<String> jcbNivelEstudios;
    private javax.swing.JComboBox<String> jcbTipoEstudio;
    private javax.swing.JFormattedTextField jftfEstudioDesde;
    private javax.swing.JFormattedTextField jftfEstudioHasta;
    private javax.swing.JFormattedTextField jftfExperienciaDesde;
    private javax.swing.JFormattedTextField jftfExperienciaHasta;
    private javax.swing.JLabel jlTituloObtenido;
    private javax.swing.JLabel jlbCaracter;
    private javax.swing.JLabel jlbCelular;
    private javax.swing.JLabel jlbDescripcion;
    private javax.swing.JLabel jlbEntidad;
    private javax.swing.JLabel jlbExperienciaHasta;
    private javax.swing.JLabel jlbHasta;
    private javax.swing.JLabel jlbIntensidad;
    private javax.swing.JLabel jlbLugarEstudios;
    private javax.swing.JLabel jlbNivelEstudios;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbNombres;
    private javax.swing.JLabel jlbOcupacion;
    private javax.swing.JLabel jlbPeriodo;
    private javax.swing.JLabel jlbTipoEstudio;
    private javax.swing.JLabel jlbTipoReferencia;
    private javax.swing.JLabel jlbduracion;
    private javax.swing.JPanel jpEstudios;
    private javax.swing.JPanel jpExperiencia;
    private javax.swing.JPanel jpOtrosEstudios;
    private javax.swing.JPanel jpReferenciaPersonal;
    private javax.swing.JRadioButton jrbFamiliar;
    private javax.swing.JRadioButton jrbPersonal;
    private javax.swing.JScrollPane jspDescripcion;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTextField jtfEntidad;
    private javax.swing.JTextField jtfIntensidad;
    private javax.swing.JTextField jtfLugarEstudios;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombres;
    private javax.swing.JTextField jtfOcupacion;
    private javax.swing.JTextField jtfTelefono;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
