/*
 * Copyright (C) 2017 Wilman Ortiz Navarro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package co.com.sistema.sistemainformacion.view;

/**
 *
 * @author Wilman Ortiz Navarro
 */
public class FormUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormUsuarios
     */
    public FormUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRegistroUsuarios = new javax.swing.JPanel();
        jpImagen = new javax.swing.JPanel();
        jlbImagenUsuario = new javax.swing.JLabel();
        jlbNombres = new javax.swing.JLabel();
        jlbApellidos = new javax.swing.JLabel();
        jlbFecha = new javax.swing.JLabel();
        jlbLugarNacimiento = new javax.swing.JLabel();
        jlbCedula = new javax.swing.JLabel();
        jlbEstadoCivil = new javax.swing.JLabel();
        jlbDireccion = new javax.swing.JLabel();
        jlbTelefono = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jtfNombres = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jtfFecha = new javax.swing.JTextField();
        jtfLugarNacimiento = new javax.swing.JTextField();
        jtfCedula = new javax.swing.JTextField();
        jtfDireccion = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfCelular = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jcbEstadoCivil = new javax.swing.JComboBox<>();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro Usuarios");

        jpRegistroUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Informacion Usuarios: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 15))); // NOI18N

        jpImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlbImagenUsuario.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbImagenUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbImagenUsuario.setText("Imagen...");

        javax.swing.GroupLayout jpImagenLayout = new javax.swing.GroupLayout(jpImagen);
        jpImagen.setLayout(jpImagenLayout);
        jpImagenLayout.setHorizontalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbImagenUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        jpImagenLayout.setVerticalGroup(
            jpImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbImagenUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        jlbNombres.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbNombres.setText("Nombres:");

        jlbApellidos.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbApellidos.setText("Apellidos:");

        jlbFecha.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbFecha.setText("Fecha Nacimiento:");

        jlbLugarNacimiento.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbLugarNacimiento.setText("Lugar de Nacimiento: ");

        jlbCedula.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbCedula.setText("Cédula de Ciudadanía:");

        jlbEstadoCivil.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbEstadoCivil.setText("Estado Civil:");

        jlbDireccion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbDireccion.setText("Dirección de Residencia:");

        jlbTelefono.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbTelefono.setText("Teléfono: ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel9.setText("Celular:");

        jlbEmail.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jlbEmail.setText("E-Mail:");

        jtfNombres.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfApellidos.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfFecha.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfLugarNacimiento.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfCedula.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfDireccion.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfTelefono.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfCelular.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jtfEmail.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jcbEstadoCivil.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jcbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpRegistroUsuariosLayout = new javax.swing.GroupLayout(jpRegistroUsuarios);
        jpRegistroUsuarios.setLayout(jpRegistroUsuariosLayout);
        jpRegistroUsuariosLayout.setHorizontalGroup(
            jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDireccion)
                            .addComponent(jlbTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDireccion)
                            .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                                .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEmail)
                            .addComponent(jLabel9))
                        .addGap(119, 119, 119)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addComponent(jlbCedula)
                        .addGap(22, 22, 22)
                        .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEstadoCivil)
                            .addComponent(jlbNombres))
                        .addGap(88, 88, 88)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                                .addComponent(jcbEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(147, 147, 147))))
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addComponent(jlbLugarNacimiento)
                        .addGap(27, 27, 27)
                        .addComponent(jtfLugarNacimiento))
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbFecha)
                            .addComponent(jlbApellidos))
                        .addGap(47, 47, 47)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRegistroUsuariosLayout.setVerticalGroup(
            jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegistroUsuariosLayout.createSequentialGroup()
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNombres)
                            .addComponent(jtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbApellidos))
                        .addGap(18, 18, 18)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbFecha))
                        .addGap(18, 18, 18)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbLugarNacimiento))
                        .addGap(18, 18, 18)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCedula))
                        .addGap(20, 20, 20)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbEstadoCivil)
                            .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbDireccion)
                            .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTelefono)
                            .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpRegistroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jbtnRegistrar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jbtnRegistrar.setMnemonic('R');
        jbtnRegistrar.setText("Registrar");

        jbtnLimpiar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jbtnLimpiar.setMnemonic('L');
        jbtnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpRegistroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpRegistroUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JComboBox<String> jcbEstadoCivil;
    private javax.swing.JLabel jlbApellidos;
    private javax.swing.JLabel jlbCedula;
    private javax.swing.JLabel jlbDireccion;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbEstadoCivil;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbImagenUsuario;
    private javax.swing.JLabel jlbLugarNacimiento;
    private javax.swing.JLabel jlbNombres;
    private javax.swing.JLabel jlbTelefono;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JPanel jpRegistroUsuarios;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfCedula;
    private javax.swing.JTextField jtfCelular;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfLugarNacimiento;
    private javax.swing.JTextField jtfNombres;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
